import "./env.d.ts";
import { assert, assertEquals } from "@std/assert";
import type { SummaryJson } from "@clipfeed/shared/types";
import {
  aggregateFaithfulnessVerdict,
  buildFaithfulnessClaims,
  buildFaithfulnessJudgePrompt,
  DEFAULT_FAITHFULNESS_JUDGE_MODEL,
  incrementFaithfulnessCallCounter,
  parseFaithfulnessCheckEnabled,
  parseFaithfulnessEnforceEnabled,
  parseJudgeResponse,
  readFaithfulnessCallCount,
  resolveFaithfulnessJudgeModel,
  runFaithfulnessCheck,
} from "./faithfulness.ts";

// --- config parsing ---

Deno.test("parseFaithfulnessCheckEnabled: default true when unset/empty", () => {
  assertEquals(parseFaithfulnessCheckEnabled(undefined), true);
  assertEquals(parseFaithfulnessCheckEnabled(""), true);
  assertEquals(parseFaithfulnessCheckEnabled("   "), true);
});

Deno.test("parseFaithfulnessCheckEnabled: only the literal 'false' (any case/whitespace) disables", () => {
  assertEquals(parseFaithfulnessCheckEnabled("false"), false);
  assertEquals(parseFaithfulnessCheckEnabled("FALSE"), false);
  assertEquals(parseFaithfulnessCheckEnabled("  False  "), false);
});

Deno.test("parseFaithfulnessCheckEnabled: garbage stays enabled (defensive default-on)", () => {
  assertEquals(parseFaithfulnessCheckEnabled("nope"), true);
  assertEquals(parseFaithfulnessCheckEnabled("0"), true);
});

Deno.test("parseFaithfulnessEnforceEnabled: default false when unset/empty/garbage", () => {
  assertEquals(parseFaithfulnessEnforceEnabled(undefined), false);
  assertEquals(parseFaithfulnessEnforceEnabled(""), false);
  assertEquals(parseFaithfulnessEnforceEnabled("false"), false);
  assertEquals(parseFaithfulnessEnforceEnabled("yes"), false);
});

Deno.test("parseFaithfulnessEnforceEnabled: only the literal 'true' (any case/whitespace) enables", () => {
  assertEquals(parseFaithfulnessEnforceEnabled("true"), true);
  assertEquals(parseFaithfulnessEnforceEnabled("TRUE"), true);
  assertEquals(parseFaithfulnessEnforceEnabled("  True  "), true);
});

Deno.test("resolveFaithfulnessJudgeModel: default when unset/empty, passthrough when set", () => {
  assertEquals(resolveFaithfulnessJudgeModel(undefined), DEFAULT_FAITHFULNESS_JUDGE_MODEL);
  assertEquals(resolveFaithfulnessJudgeModel(""), DEFAULT_FAITHFULNESS_JUDGE_MODEL);
  assertEquals(resolveFaithfulnessJudgeModel("@cf/custom/model"), "@cf/custom/model");
});

// --- claim building ---

const SUMMARY: SummaryJson = {
  title_ru: "т",
  title_en: "t",
  tldr_ru: "р",
  tldr_en: "the tldr sentence",
  body_ru: ["п1", "п2"],
  body_en: ["paragraph one", "paragraph two"],
  bullets_ru: ["б1", "б2"],
  bullets_en: ["bullet one", "bullet two"],
  tags: ["tag"],
  lang_original: "en",
};

Deno.test("buildFaithfulnessClaims: RU fields only (Task 35 Part A — RU is always present, EN may not be), tldr then bullets then body, numbered from 1", () => {
  const claims = buildFaithfulnessClaims(SUMMARY);
  assertEquals(claims, [
    { i: 1, text: "р" },
    { i: 2, text: "б1" },
    { i: 3, text: "б2" },
    { i: 4, text: "п1" },
    { i: 5, text: "п2" },
  ]);
});

Deno.test("buildFaithfulnessJudgePrompt: contains the schema, source/claims tags, and injection-hardening", () => {
  const prompt = buildFaithfulnessJudgePrompt(
    [{ i: 1, text: "claim one" }],
    "the source text",
  );
  assert(prompt.includes("supported"));
  assert(prompt.includes("unsupported"));
  assert(prompt.includes("contradicted"));
  assert(prompt.includes("<source>"));
  assert(prompt.includes("the source text"));
  assert(prompt.includes("</source>"));
  assert(prompt.includes("<claims>"));
  assert(prompt.includes("1. claim one"));
  assert(prompt.includes("</claims>"));
  assert(prompt.toLowerCase().includes("ignore"));
});

// Task 35 Part A §5: with EN no longer generated by default, the claims fed
// to the judge are usually Russian while the source is usually whatever
// language the article was actually written in — the prompt must say this
// explicitly and ask the judge to verify meaning, not wording/language.
Deno.test("buildFaithfulnessJudgePrompt: states claims/source may be in different languages and to verify MEANING", () => {
  const prompt = buildFaithfulnessJudgePrompt([{ i: 1, text: "claim one" }], "source");
  assert(prompt.toLowerCase().includes("different languages"));
  assert(prompt.toUpperCase().includes("MEANING"));
});

// --- judge response parsing ---

Deno.test("parseJudgeResponse: valid JSON parses claims and notes", () => {
  const raw = JSON.stringify({
    claims: [{ i: 1, verdict: "supported", evidence: "quoted span" }],
    notes: "looks fine",
  });
  const parsed = parseJudgeResponse(raw);
  assertEquals(parsed, {
    claims: [{ i: 1, verdict: "supported", evidence: "quoted span" }],
    notes: "looks fine",
  });
});

Deno.test("parseJudgeResponse: fenced JSON is stripped before parsing", () => {
  const raw = "```json\n" + JSON.stringify({
    claims: [{ i: 1, verdict: "unsupported", evidence: "" }],
    notes: "",
  }) + "\n```";
  const parsed = parseJudgeResponse(raw);
  assertEquals(parsed?.claims[0].verdict, "unsupported");
});

Deno.test("parseJudgeResponse: missing notes defaults to empty string, not a parse failure", () => {
  const raw = JSON.stringify({ claims: [{ i: 1, verdict: "supported", evidence: "x" }] });
  const parsed = parseJudgeResponse(raw);
  assertEquals(parsed?.notes, "");
});

Deno.test("parseJudgeResponse: not JSON at all -> null", () => {
  assertEquals(parseJudgeResponse("not json"), null);
});

Deno.test("parseJudgeResponse: missing claims array -> null", () => {
  assertEquals(parseJudgeResponse(JSON.stringify({ notes: "x" })), null);
});

Deno.test("parseJudgeResponse: invalid verdict enum -> null", () => {
  const raw = JSON.stringify({ claims: [{ i: 1, verdict: "maybe", evidence: "x" }] });
  assertEquals(parseJudgeResponse(raw), null);
});

Deno.test("parseJudgeResponse: claim missing evidence -> null", () => {
  const raw = JSON.stringify({ claims: [{ i: 1, verdict: "supported" }] });
  assertEquals(parseJudgeResponse(raw), null);
});

// Regression: observed live — the judge prompt only asks for an evidence
// quote on supported/contradicted claims, and the model reliably omits the
// field for "unsupported" ones. That is a valid response, not a parse
// failure; evidence should default to "" rather than rejecting the claim.
Deno.test("parseJudgeResponse: unsupported claim missing evidence is accepted, defaults to empty string", () => {
  const raw = JSON.stringify({ claims: [{ i: 1, verdict: "unsupported" }] });
  const parsed = parseJudgeResponse(raw);
  assertEquals(parsed, { claims: [{ i: 1, verdict: "unsupported", evidence: "" }], notes: "" });
});

Deno.test("parseJudgeResponse: contradicted claim missing evidence -> null (evidence required)", () => {
  const raw = JSON.stringify({ claims: [{ i: 1, verdict: "contradicted" }] });
  assertEquals(parseJudgeResponse(raw), null);
});

// Regression: observed live against @cf/meta/llama-3.3-70b-instruct-fp8-fast
// via getPlatformProxy — Workers AI's `{ response }` wrapper returned
// `response` as an already-parsed object (not a JSON string) for this
// model/prompt, which the string-only parser silently rejected as
// unparseable on every real call. Mirrors summarize.ts's parseWorkersAiResult
// handling of the same string/object duality.
Deno.test("parseJudgeResponse: already-parsed object response (not a string) is accepted", () => {
  const raw = {
    claims: [{ i: 1, verdict: "supported", evidence: "quoted span" }],
    notes: "looks fine",
  };
  const parsed = parseJudgeResponse(raw);
  assertEquals(parsed, {
    claims: [{ i: 1, verdict: "supported", evidence: "quoted span" }],
    notes: "looks fine",
  });
});

Deno.test("parseJudgeResponse: object response missing claims array -> null", () => {
  assertEquals(parseJudgeResponse({ notes: "x" }), null);
});

// --- aggregation ---

function claim(verdict: "supported" | "unsupported" | "contradicted"): {
  i: number;
  verdict: "supported" | "unsupported" | "contradicted";
  evidence: string;
} {
  return { i: 1, verdict, evidence: "" };
}

Deno.test("aggregateFaithfulnessVerdict: any contradicted claim -> fail, regardless of ratio", () => {
  const claims = [
    claim("supported"),
    claim("supported"),
    claim("supported"),
    claim("contradicted"),
  ];
  assertEquals(aggregateFaithfulnessVerdict(claims), "fail");
});

Deno.test("aggregateFaithfulnessVerdict: unsupported ratio > 0.5 -> fail", () => {
  const claims = [
    claim("unsupported"),
    claim("unsupported"),
    claim("unsupported"),
    claim("supported"),
  ];
  assertEquals(aggregateFaithfulnessVerdict(claims), "fail");
});

Deno.test("aggregateFaithfulnessVerdict: unsupported ratio > 0.25 and <= 0.5 -> weak", () => {
  const claims = [claim("unsupported"), claim("supported"), claim("supported")];
  assertEquals(aggregateFaithfulnessVerdict(claims), "weak");
});

Deno.test("aggregateFaithfulnessVerdict: unsupported ratio exactly 0.25 -> pass (boundary, not '>')", () => {
  const claims = [claim("unsupported"), claim("supported"), claim("supported"), claim("supported")];
  assertEquals(aggregateFaithfulnessVerdict(claims), "pass");
});

Deno.test("aggregateFaithfulnessVerdict: all supported -> pass", () => {
  assertEquals(
    aggregateFaithfulnessVerdict([claim("supported"), claim("supported")]),
    "pass",
  );
});

Deno.test("aggregateFaithfulnessVerdict: empty claim set -> pass (defensive, shouldn't happen in practice)", () => {
  assertEquals(aggregateFaithfulnessVerdict([]), "pass");
});

// --- KV call counter ---

class FakeKV {
  store = new Map<string, string>();
  get(key: string): Promise<string | null> {
    return Promise.resolve(this.store.get(key) ?? null);
  }
  put(key: string, value: string): Promise<void> {
    this.store.set(key, value);
    return Promise.resolve();
  }
}

Deno.test("incrementFaithfulnessCallCounter / readFaithfulnessCallCount: round-trip and accumulate", async () => {
  const cache = new FakeKV() as unknown as KVNamespace;
  const now = new Date("2026-01-01T00:00:00.000Z");
  assertEquals(await readFaithfulnessCallCount(cache, now), 0);
  await incrementFaithfulnessCallCounter(cache, now);
  await incrementFaithfulnessCallCounter(cache, now);
  assertEquals(await readFaithfulnessCallCount(cache, now), 2);
});

// --- runFaithfulnessCheck: end-to-end orchestration ---

function fakeAi(responses: unknown[]): Ai {
  let call = 0;
  return {
    run(): Promise<unknown> {
      const response = responses[Math.min(call, responses.length - 1)];
      call += 1;
      return Promise.resolve(response);
    },
  };
}

Deno.test("runFaithfulnessCheck: valid first response parses and aggregates, no retry needed", async () => {
  const judgeJson = JSON.stringify({
    claims: SUMMARY.bullets_ru.map((_t, i) => ({ i: i + 1, verdict: "supported", evidence: "x" })),
    notes: "ok",
  });
  const ai = fakeAi([{ response: judgeJson }]);
  const result = await runFaithfulnessCheck(ai, "test-model", "source text", {
    ...SUMMARY,
    bullets_ru: ["one", "two"],
    body_ru: [],
  });
  assertEquals(result.verdict, "pass");
  assert("claims" in result.json);
});

Deno.test("runFaithfulnessCheck: unparseable first response retries once with a corrective message and uses that result", async () => {
  const goodJson = JSON.stringify({
    claims: [{ i: 1, verdict: "unsupported", evidence: "" }],
    notes: "",
  });
  let secondPrompt = "";
  let call = 0;
  const ai: Ai = {
    run(_model: string, input: unknown): Promise<unknown> {
      const prompt = (input as { messages: { content: string }[] }).messages[0].content;
      if (call === 1) secondPrompt = prompt;
      call += 1;
      return Promise.resolve({ response: call === 1 ? "not json at all" : goodJson });
    },
  };
  const result = await runFaithfulnessCheck(ai, "test-model", "source", {
    ...SUMMARY,
    bullets_ru: [],
    body_ru: [],
  });
  assertEquals(result.verdict, "fail"); // single unsupported claim, ratio 1.0
  assert(secondPrompt.includes("previous response was not valid JSON"));
});

Deno.test("runFaithfulnessCheck: Workers AI returning response as an object (not a string) still parses", async () => {
  const ai = fakeAi([{
    response: {
      claims: SUMMARY.bullets_ru.map((_t, i) => ({
        i: i + 1,
        verdict: "supported",
        evidence: "x",
      })),
      notes: "ok",
    },
  }]);
  const result = await runFaithfulnessCheck(ai, "test-model", "source text", {
    ...SUMMARY,
    bullets_ru: ["one", "two"],
    body_ru: [],
  });
  assertEquals(result.verdict, "pass");
  assert("claims" in result.json);
});

Deno.test("runFaithfulnessCheck: both attempts unparseable -> verdict null + {error}, never throws", async () => {
  const ai = fakeAi([{ response: "garbage" }, { response: "still garbage" }]);
  const result = await runFaithfulnessCheck(ai, "test-model", "source", {
    ...SUMMARY,
    bullets_ru: [],
    body_ru: [],
  });
  assertEquals(result.verdict, null);
  assertEquals(result.json, { error: "judge unparseable" });
  assertEquals(result.counts, { supported: 0, unsupported: 0, contradicted: 0 });
});

Deno.test("runFaithfulnessCheck: ai.run throwing on both attempts -> same null-result, never throws", async () => {
  const ai: Ai = { run: () => Promise.reject(new Error("binding unavailable")) };
  const result = await runFaithfulnessCheck(ai, "test-model", "source", {
    ...SUMMARY,
    bullets_ru: [],
    body_ru: [],
  });
  assertEquals(result.verdict, null);
  assertEquals(result.json, { error: "judge unparseable" });
});

Deno.test("runFaithfulnessCheck: checkedAt is always set, even on judge failure", async () => {
  const ai: Ai = { run: () => Promise.reject(new Error("down")) };
  const now = new Date("2026-03-01T12:00:00.000Z");
  const result = await runFaithfulnessCheck(
    ai,
    "test-model",
    "source",
    { ...SUMMARY, bullets_ru: [], body_ru: [] },
    now,
  );
  assertEquals(result.checkedAt, "2026-03-01T12:00:00.000Z");
});
